import 'package:get/get.dart';

class I18 extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': 'Home',
          'account': 'Account',
          'user': 'Username',
          'password': 'Password',
          'button-session': 'Log in',
          'google-btn': 'Sign up with Google.',
          'facebook-btn': 'Sign up with Facebook.',
          'apple-btn': 'Sign up with Apple.',
          'bad-request': 'Bad request',
          'method-not-allowed': 'Method Not Allowed',
          'required': 'The field is required',
          'email-format': 'The email format is wrong',
          'guess': 'Guess',
          'my-cards': 'My cards',
          'logout': 'Log out',
          'change-password': 'Change password',
          'receive-notifications': 'Receive notifications',
          'cancel': 'Cancel',
          'coupon': 'Coupon',
          'golf-courses': 'Golf courses',
          'regulations': 'Regulations',
          'activate': 'Activate',
          'membership': 'Membership',
          'activation-code': 'Activation Code',
          'all-services': 'All Services.',
          'assemblies': 'Assemblies',
          'balances': 'Balances',
          'publications': 'Publications',
          'services': 'Services',
          'tickets': 'Tickets',
          'polls': 'Polls',
          'current-balance': 'Current balance',
          'notifications': 'Notifications',
          'delete': 'Delete',
        },
        'es': {
          'home': 'Inicio',
          'account': 'Cuenta',
          'user': 'Usuario',
          'password': 'Contraseña',
          'button-session': 'Iniciar sessión.',
          'google-btn': 'Regístrate con Google.',
          'facebook-btn': 'Regístrate con Facebook.',
          'apple-btn': 'Regístrate con Apple.',
          'bad-request': 'Solicitud incorrecta',
          'method-not-allowed': 'Método no permitido',
          'required': 'El campo es requerido',
          'email-format': 'El formato de correo electrónico es incorrecto',
          'guess': 'Invitado',
          'my-cards': 'Mis tarjetas',
          'logout': 'Cerrar sesión',
          'change-password': 'Cambiar contraseña',
          'receive-notifications': 'Recibir notificaciones',
          'cancel': 'Cancelar',
          'coupon': 'Cupón',
          'golf-courses': 'Campos de golf',
          'regulations': 'Reglamentos',
          'activate': 'Activar',
          'membership': 'Membresía',
          'activation-code': 'Código de activación',
          'all-services': 'Todos los servicios.',
          'assemblies': 'Asambleas',
          'balances': 'Saldos',
          'publications': 'Publicaciones',
          'services': 'Servicios',
          'tickets': 'Tickets',
          'polls': 'Encuestas',
          'current-balance': 'Saldo actual',
          'notifications': 'Notificaciones',
          'delete': 'Eliminar',
        }
      };
}
