import 'package:get/get.dart';

class I18 extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': 'Home',
          'billboard': 'Billboard',
          'comming': 'Comming soon',
          'account': 'Account',
          'try': 'Try again',
          'wifi': 'Internet connection is available',
          'url-valid': 'Please enter a valid url',
          'url-access': 'This url could not be accessed',
          'guess': 'Guess',
          'my-cards': 'My cards',
          'logout': 'Log out',
          'login': 'Log In',
          'change-password': 'Change password',
          'receive-notifications': 'Receive notifications',
          'password': 'Password',
          'button-session': 'Log in',
          'google-btn': 'Sign up with Google.',
          'facebook-btn': 'Sign up with Facebook.',
          'apple-btn': 'Sign up with Apple.',
          'bad-request': 'Bad request',
          'method-not-allowed': 'Method Not Allowed',
          'required': 'The field is required',
          'email-format': 'The email format is wrong',
          'share': 'Share',
          'card': 'Card',
        },
        'es': {
          'home': 'Inicio',
          'billboard': 'Cartelera',
          'comming': 'Próximamente',
          'account': 'Cuenta',
          'try': 'Intentar de nuevo',
          'wifi': 'Conexión a internet disponible',
          'url-valid': 'Favor de ingresar una url válida',
          'url-access': 'No se pudo acceder a esta url',
          'guess': 'Invitado',
          'my-cards': 'Mis tarjetas',
          'logout': 'Cerrar sesión',
          'login': 'Iniciar sesión',
          'change-password': 'Cambiar contraseña',
          'receive-notifications': 'Recibir notificaciones',
          'user': 'Usuario',
          'password': 'Contraseña',
          'button-session': 'Iniciar sessión.',
          'google-btn': 'Regístrate con Google.',
          'facebook-btn': 'Regístrate con Facebook.',
          'apple-btn': 'Regístrate con Apple.',
          'bad-request': 'Solicitud incorrecta',
          'method-not-allowed': 'Método no permitido',
          'required': 'El campo es requerido',
          'email-format': 'El formato de correo electrónico es incorrecto',
          'share': 'Compartir',
          'card': 'Tarjeta',
        }
      };
}
